DROP TRIGGER IF EXISTS tr_timeline_posts_updated_at ON timeline_posts;
DROP TRIGGER IF EXISTS tr_forum_posts_updated_at ON forum_posts;
DROP TRIGGER IF EXISTS tr_maintenance_updated_at ON maintenance_requests;
DROP TRIGGER IF EXISTS tr_due_payments_updated_at ON due_payments;
DROP TRIGGER IF EXISTS tr_units_updated_at ON units;
DROP TRIGGER IF EXISTS tr_buildings_updated_at ON buildings;
DROP TRIGGER IF EXISTS tr_users_updated_at ON users;
DROP FUNCTION IF EXISTS update_updated_at();

DROP TABLE IF EXISTS building_members CASCADE;
DROP TABLE IF EXISTS poll_votes CASCADE;
DROP TABLE IF EXISTS poll_options CASCADE;
DROP TABLE IF EXISTS polls CASCADE;
DROP TABLE IF EXISTS timeline_comments CASCADE;
DROP TABLE IF EXISTS timeline_likes CASCADE;
DROP TABLE IF EXISTS timeline_media CASCADE;
DROP TABLE IF EXISTS timeline_posts CASCADE;
DROP TABLE IF EXISTS forum_votes CASCADE;
DROP TABLE IF EXISTS forum_comments CASCADE;
DROP TABLE IF EXISTS forum_posts CASCADE;
DROP TABLE IF EXISTS forum_categories CASCADE;
DROP TABLE IF EXISTS notification_preferences CASCADE;
DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS vendors CASCADE;
DROP TABLE IF EXISTS maintenance_photos CASCADE;
DROP TABLE IF EXISTS maintenance_requests CASCADE;
DROP TABLE IF EXISTS expenses CASCADE;
DROP TABLE IF EXISTS due_payments CASCADE;
DROP TABLE IF EXISTS dues_plans CASCADE;
DROP TABLE IF EXISTS vehicles CASCADE;
DROP TABLE IF EXISTS unit_residents CASCADE;
DROP TABLE IF EXISTS units CASCADE;
DROP TABLE IF EXISTS buildings CASCADE;
DROP TABLE IF EXISTS refresh_tokens CASCADE;
DROP TABLE IF EXISTS users CASCADE;

DROP TYPE IF EXISTS visibility_type;
DROP TYPE IF EXISTS timeline_post_type;
DROP TYPE IF EXISTS maintenance_status;
DROP TYPE IF EXISTS maintenance_priority;
DROP TYPE IF EXISTS payment_status;
DROP TYPE IF EXISTS resident_type;
DROP TYPE IF EXISTS unit_status;
DROP TYPE IF EXISTS user_role;
